import XCTest
import Foundation
@testable import TesseraCore

// MARK: - DrawingStoreTests
//
// Contract sources: DrawingStore.swift's own doc comment ("every
// mutation appends a signed receipt... Receipt contract"),
// testing-doctrine.md rule 1 ("no receipt without a mutation" is a
// standing rule; its tests are mandatory per store method, both
// directions), and the KNOWN, AUDITED BUG named in this cluster's task
// brief (docs/p1-post-claim-audit-2026-08-15.md Class A item 1):
// DrawingStore's layer-mutation methods upsert + emit a receipt even
// when the underlying pure Drawing mutator no-op'd.
//
// DB-GATED (doctrine rule 11): every test in this file talks to a real
// TesseraDataLayer (Postgres + Valkey) and is skipped unless
// TESSERA_DB_INTEGRATION=1 is set AND the stores are actually reachable.
// Each contract here has an UNGATED SHADOW in DrawingTests.swift, which
// exercises the exact same "no-op on unknown id" contract directly
// against Drawing's pure mutators (the logic DrawingStore wraps) with
// no DB dependency - so a plain `swift test` still exercises the
// business logic even though the store-level wiring (and the bug in
// it) is only visible under the DB-gated pass.

private enum DrawTestDataLayer {
    /// Starts a real `TesseraDataLayer` against the default local
    /// Postgres/Valkey configuration. Skips the calling test (via
    /// `XCTSkip`) rather than failing when TESSERA_DB_INTEGRATION isn't
    /// set, or when it is set but the local stores aren't actually up -
    /// this is integration infrastructure, not something this test pass
    /// can guarantee is running.
    static func startedOrSkip() async throws -> TesseraDataLayer {
        guard ProcessInfo.processInfo.environment["TESSERA_DB_INTEGRATION"] == "1" else {
            throw XCTSkip("TESSERA_DB_INTEGRATION=1 not set - skipping DB-gated DrawingStore test (see rule 11's ungated shadow in DrawingTests.swift for the same contract without a DB).")
        }
        let layer = TesseraDataLayer()
        let outcome = await layer.start()
        guard case .ready = outcome else {
            throw XCTSkip("TesseraDataLayer did not reach .ready (\(outcome)) - local Postgres/Valkey not reachable.")
        }
        return layer
    }
}

final class DrawingStoreTests: DoctrineTestCase {
    override var doctrineTimeoutSeconds: TimeInterval { DoctrineTimeout.standard }

    // MARK: - Upsert: receipt + persistence (rule 1, mutation direction)

    func testUpsertOfNewDrawingEmitsExactlyOneUpsertReceiptWithDocumentedPayloadKeys() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let drawing = Drawing(title: "Gate Test Drawing")

        let saved = try await store.upsert(drawing)
        let receipts = try await store.receipts(forDrawing: saved.id)

        XCTAssertEqual(receipts.count, 1)
        let receipt = try XCTUnwrap(receipts.first)
        XCTAssertEqual(receipt.receiptType, DrawingReceiptType.upsert.rawValue)
        XCTAssertEqual(receipt.payload["title"], .string("Gate Test Drawing"))
        XCTAssertEqual(receipt.payload["shapeCount"], .number(0))

        let fetched = try await store.get(id: saved.id)
        XCTAssertEqual(fetched?.title, "Gate Test Drawing")
    }

    // MARK: - Delete: error path (not-found throws without writing)

    func testDeleteOfUnknownIDReturnsFalseAndEmitsNoReceipt() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let unknownID = UUID()

        let didDelete = try await store.delete(id: unknownID)
        XCTAssertFalse(didDelete)

        let receipts = try await store.receipts(forDrawing: unknownID)
        XCTAssertEqual(receipts.count, 0, "a delete of a nonexistent drawing must not append a delete receipt")
    }

    // MARK: - addLayer: always mutates, exactly one receipt (NOT a
    // no-op-detectable case: DrawLayer's own id is freshly generated by
    // the caller, so there is no "unknown id" for addLayer to reject -
    // Drawing.addingLayer always appends, per its own doc comment).

    func testAddLayerAlwaysMutatesAndEmitsExactlyOneLayerAddedReceipt() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let drawing = try await store.upsert(Drawing(title: "AddLayer Gate Test"))
        let newLayer = DrawLayer(name: "Background")

        let updated = try await store.addLayer(newLayer, to: drawing.id)
        XCTAssertEqual(updated.layers.map(\.id), [newLayer.id])

        let receipts = try await store.receipts(forDrawing: drawing.id)
        let layerAddedReceipts = receipts.filter { $0.receiptType == DrawingReceiptType.layerAdded.rawValue }
        XCTAssertEqual(layerAddedReceipts.count, 1)
    }

    // MARK: - No-op layer mutations: SUSPECTED BUG (doctrine rule 1,
    // suspected-bug protocol). Each of these asserts ZERO receipts for a
    // mutation on an unknown layer id, matching the pure Drawing mutator's
    // own no-op contract (see DrawingTests.swift). Confirmed failing at
    // HEAD per docs/p1-post-claim-audit-2026-08-15.md Class A item 1.

    func testRemoveLayerOfUnknownIDEmitsNoReceiptAndDoesNotPersist() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let drawing = try await store.upsert(Drawing(title: "RemoveLayer NoOp Gate Test"))
        let unknownLayerID = UUID()

        // XCTExpectFailure's failingBlock is synchronous (`() throws -> Void`),
        // so the async setup/action/measurement happens here, before the
        // block - only the plain assertion on already-computed values runs
        // inside it.
        let receiptsBefore = try await store.receipts(forDrawing: drawing.id).count
        _ = try? await store.removeLayer(unknownLayerID, from: drawing.id)
        let receiptsAfter = try await store.receipts(forDrawing: drawing.id).count

        XCTAssertEqual(receiptsAfter, receiptsBefore, "no-op layer removal must not append a receipt")
    }

    func testRenameLayerOfUnknownIDEmitsNoReceiptAndDoesNotPersist() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let drawing = try await store.upsert(Drawing(title: "RenameLayer NoOp Gate Test"))
        let unknownLayerID = UUID()

        let receiptsBefore = try await store.receipts(forDrawing: drawing.id).count
        _ = try? await store.renameLayer(unknownLayerID, to: "New Name", in: drawing.id)
        let receiptsAfter = try await store.receipts(forDrawing: drawing.id).count

        XCTAssertEqual(receiptsAfter, receiptsBefore, "no-op layer rename must not append a receipt")
    }

    func testReorderLayersWithMismatchedOrderEmitsNoReceiptAndDoesNotPersist() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        var drawing = try await store.upsert(Drawing(title: "ReorderLayers NoOp Gate Test"))
        let onlyLayer = DrawLayer(name: "Only")
        drawing = try await store.addLayer(onlyLayer, to: drawing.id)
        let mismatchedOrder = [onlyLayer.id, UUID()]

        let receiptsBefore = try await store.receipts(forDrawing: drawing.id).count
        _ = try? await store.reorderLayers(mismatchedOrder, in: drawing.id)
        let receiptsAfter = try await store.receipts(forDrawing: drawing.id).count

        XCTAssertEqual(receiptsAfter, receiptsBefore, "no-op layer reorder must not append a receipt")
    }

    func testSetLayerVisibilityOfUnknownIDEmitsNoReceiptAndDoesNotPersist() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let drawing = try await store.upsert(Drawing(title: "SetLayerVisibility NoOp Gate Test"))
        let unknownLayerID = UUID()

        let receiptsBefore = try await store.receipts(forDrawing: drawing.id).count
        _ = try? await store.setLayerVisibility(unknownLayerID, isVisible: false, in: drawing.id)
        let receiptsAfter = try await store.receipts(forDrawing: drawing.id).count

        XCTAssertEqual(receiptsAfter, receiptsBefore, "no-op visibility change must not append a receipt")
    }

    func testSetLayerLockOfUnknownIDEmitsNoReceiptAndDoesNotPersist() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let drawing = try await store.upsert(Drawing(title: "SetLayerLock NoOp Gate Test"))
        let unknownLayerID = UUID()

        let receiptsBefore = try await store.receipts(forDrawing: drawing.id).count
        _ = try? await store.setLayerLock(unknownLayerID, isLocked: true, in: drawing.id)
        let receiptsAfter = try await store.receipts(forDrawing: drawing.id).count

        XCTAssertEqual(receiptsAfter, receiptsBefore, "no-op lock change must not append a receipt")
    }

    // MARK: - Shape mutation error path

    func testDeleteShapeOfUnknownIDThrowsShapeNotFoundWithoutPersisting() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let drawing = try await store.upsert(Drawing(title: "DeleteShape ErrorPath Gate Test"))
        let unknownShapeID = UUID()

        do {
            _ = try await store.deleteShape(unknownShapeID, for: drawing.id)
            XCTFail("expected DrawingStoreError.shapeNotFound")
        } catch DrawingStoreError.shapeNotFound(let id) {
            XCTAssertEqual(id, unknownShapeID)
        }

        let receipts = try await store.receipts(forDrawing: drawing.id)
        let deleteShapeReceipts = receipts.filter { $0.receiptType == DrawingReceiptType.deleteShape.rawValue }
        XCTAssertEqual(deleteShapeReceipts.count, 0, "a failed shape delete must not append a deleteShape receipt")
    }

    // MARK: - Shape insert: receipt payload keys

    func testInsertShapeEmitsExactlyOneReceiptWithShapeIDAndKind() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let drawing = try await store.upsert(Drawing(title: "InsertShape Gate Test"))
        let shape = Shape(kind: .ellipse, geometry: ShapeGeometry(x: 0, y: 0, width: 5, height: 5))

        _ = try await store.insertShape(shape, for: drawing.id)

        let receipts = try await store.receipts(forDrawing: drawing.id)
        let insertReceipts = receipts.filter { $0.receiptType == DrawingReceiptType.insertShape.rawValue }
        XCTAssertEqual(insertReceipts.count, 1)
        XCTAssertEqual(insertReceipts.first?.payload["shapeID"], .string(shape.id.uuidString))
        XCTAssertEqual(insertReceipts.first?.payload["kind"], .string("ellipse"))
    }

    // MARK: - setGeometries: one commit, N shapes = ONE receipt
    // (P2-0 item 3, "one physical drag = one receipt = one undo unit")

    func testSetGeometriesOfMultipleShapesEmitsExactlyOneReceiptCoveringAllOfThem() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        var drawing = try await store.upsert(Drawing(title: "SetGeometries Gate Test"))
        let s1 = Shape(kind: .rect, geometry: ShapeGeometry(x: 0, y: 0, width: 10, height: 10))
        let s2 = Shape(kind: .rect, geometry: ShapeGeometry(x: 20, y: 20, width: 10, height: 10))
        drawing = try await store.insertShape(s1, for: drawing.id)
        drawing = try await store.insertShape(s2, for: drawing.id)

        var g1 = s1.geometry; g1.x += 5; g1.y += 5
        var g2 = s2.geometry; g2.x += 5; g2.y += 5
        let updated = try await store.setGeometries([s1.id: g1, s2.id: g2], for: drawing.id)

        XCTAssertEqual(updated.shape(id: s1.id)?.geometry.x, g1.x)
        XCTAssertEqual(updated.shape(id: s2.id)?.geometry.x, g2.x)

        let receipts = try await store.receipts(forDrawing: drawing.id)
        let geometryReceipts = receipts.filter { $0.receiptType == DrawingReceiptType.setGeometry.rawValue }
        XCTAssertEqual(geometryReceipts.count, 1, "moving 2 shapes in one gesture must produce exactly one setGeometry receipt, not one per shape")
        XCTAssertEqual(geometryReceipts.first?.payload["shapeCount"], .number(2))
    }

    func testSetGeometriesWithNoActualChangeEmitsNoReceipt() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        var drawing = try await store.upsert(Drawing(title: "SetGeometries NoOp Gate Test"))
        let shape = Shape(kind: .rect, geometry: ShapeGeometry(x: 0, y: 0, width: 10, height: 10))
        drawing = try await store.insertShape(shape, for: drawing.id)

        let receiptsBefore = try await store.receipts(forDrawing: drawing.id).count
        _ = try await store.setGeometries([shape.id: shape.geometry], for: drawing.id)
        let receiptsAfter = try await store.receipts(forDrawing: drawing.id).count

        XCTAssertEqual(receiptsAfter, receiptsBefore, "setting a shape's geometry to its own current value must not append a receipt")
    }

    func testSetGeometriesOfUnknownShapeIDThrowsWithoutPersisting() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let drawing = try await store.upsert(Drawing(title: "SetGeometries ErrorPath Gate Test"))
        let unknownID = UUID()

        do {
            _ = try await store.setGeometries([unknownID: ShapeGeometry(x: 0, y: 0, width: 1, height: 1)], for: drawing.id)
            XCTFail("expected DrawingStoreError.shapeNotFound")
        } catch DrawingStoreError.shapeNotFound(let id) {
            XCTAssertEqual(id, unknownID)
        }

        let receipts = try await store.receipts(forDrawing: drawing.id)
        XCTAssertTrue(receipts.filter { $0.receiptType == DrawingReceiptType.setGeometry.rawValue }.isEmpty)
    }

    // MARK: - group / ungroup: receipt + persistence (row 48, P2-0)

    func testGroupingTwoShapesSetsParentGroupIDAndEmitsExactlyOneReceipt() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        var drawing = try await store.upsert(Drawing(title: "Group Gate Test"))
        let s1 = Shape(kind: .rect, geometry: ShapeGeometry(x: 0, y: 0, width: 10, height: 10))
        let s2 = Shape(kind: .ellipse, geometry: ShapeGeometry(x: 20, y: 20, width: 10, height: 10))
        drawing = try await store.insertShape(s1, for: drawing.id)
        drawing = try await store.insertShape(s2, for: drawing.id)

        let updated = try await store.group([s1.id, s2.id], for: drawing.id)
        let groupID = updated.shape(id: s1.id)?.parentGroupID
        XCTAssertNotNil(groupID)
        XCTAssertEqual(updated.shape(id: s2.id)?.parentGroupID, groupID)

        let receipts = try await store.receipts(forDrawing: drawing.id)
        let groupReceipts = receipts.filter { $0.receiptType == DrawingReceiptType.groupShapes.rawValue }
        XCTAssertEqual(groupReceipts.count, 1)
    }

    func testGroupingFewerThanTwoShapeIDsEmitsNoReceipt() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        var drawing = try await store.upsert(Drawing(title: "Group NoOp Gate Test"))
        let s1 = Shape(kind: .rect, geometry: ShapeGeometry(x: 0, y: 0, width: 10, height: 10))
        drawing = try await store.insertShape(s1, for: drawing.id)

        let receiptsBefore = try await store.receipts(forDrawing: drawing.id).count
        _ = try await store.group([s1.id], for: drawing.id)
        let receiptsAfter = try await store.receipts(forDrawing: drawing.id).count

        XCTAssertEqual(receiptsAfter, receiptsBefore, "grouping fewer than 2 shape ids must not append a receipt")
    }

    func testUngroupingClearsParentGroupIDAndEmitsExactlyOneReceipt() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        var drawing = try await store.upsert(Drawing(title: "Ungroup Gate Test"))
        let s1 = Shape(kind: .rect, geometry: ShapeGeometry(x: 0, y: 0, width: 10, height: 10))
        let s2 = Shape(kind: .rect, geometry: ShapeGeometry(x: 20, y: 20, width: 10, height: 10))
        drawing = try await store.insertShape(s1, for: drawing.id)
        drawing = try await store.insertShape(s2, for: drawing.id)
        drawing = try await store.group([s1.id, s2.id], for: drawing.id)
        let groupID = try XCTUnwrap(drawing.shape(id: s1.id)?.parentGroupID)

        let updated = try await store.ungroup(groupID, for: drawing.id)
        XCTAssertNil(updated.shape(id: s1.id)?.parentGroupID)
        XCTAssertNil(updated.shape(id: s2.id)?.parentGroupID)

        let receipts = try await store.receipts(forDrawing: drawing.id)
        let ungroupReceipts = receipts.filter { $0.receiptType == DrawingReceiptType.ungroupShapes.rawValue }
        XCTAssertEqual(ungroupReceipts.count, 1)
    }

    func testUngroupingAnUnknownGroupIDEmitsNoReceipt() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let drawing = try await store.upsert(Drawing(title: "Ungroup NoOp Gate Test"))

        let receiptsBefore = try await store.receipts(forDrawing: drawing.id).count
        _ = try await store.ungroup(UUID(), for: drawing.id)
        let receiptsAfter = try await store.receipts(forDrawing: drawing.id).count

        XCTAssertEqual(receiptsAfter, receiptsBefore, "ungrouping an id no shape carries must not append a receipt")
    }

    // MARK: - group / ungroup pure logic (UNGATED SHADOW, doctrine rule
    // 11): DrawingStore.group/.ungroup delegate to `applyingGroup`/
    // `applyingUngroup`, kept `internal` specifically so this contract
    // is exercised by a plain `swift test` with no DB dependency -
    // mirrors `SlideStoreLayoutApplicationTests.swift`'s coverage of
    // `SlideStore.applyingLayout` the same way.

    func testApplyingGroupOfTwoKnownShapeIDsAssignsASharedFreshGroupID() {
        let s1 = Shape(kind: .rect, geometry: ShapeGeometry(x: 0, y: 0, width: 10, height: 10))
        let s2 = Shape(kind: .ellipse, geometry: ShapeGeometry(x: 20, y: 20, width: 10, height: 10))
        let drawing = Drawing.makeBlank().insertingShape(s1).insertingShape(s2)

        let result = DrawingStore.applyingGroup([s1.id, s2.id], to: drawing)
        let unwrapped = result

        XCTAssertNotNil(unwrapped)
        XCTAssertEqual(unwrapped?.drawing.shape(id: s1.id)?.parentGroupID, unwrapped?.groupID)
        XCTAssertEqual(unwrapped?.drawing.shape(id: s2.id)?.parentGroupID, unwrapped?.groupID)
        XCTAssertEqual(Set(unwrapped?.memberIDs ?? []), Set([s1.id, s2.id]))
    }

    func testApplyingGroupDropsUnknownIDsAndReturnsNilIfFewerThanTwoValidIDsRemain() {
        let s1 = Shape(kind: .rect, geometry: ShapeGeometry(x: 0, y: 0, width: 10, height: 10))
        let drawing = Drawing.makeBlank().insertingShape(s1)

        // s1 plus an id not present in the drawing: only 1 valid id remains.
        let result = DrawingStore.applyingGroup([s1.id, UUID()], to: drawing)
        XCTAssertNil(result, "fewer than 2 VALID shape ids (after dropping unknown ones) must be a no-op")
    }

    func testApplyingGroupOfEmptySelectionReturnsNil() {
        let drawing = Drawing.makeBlank()
        XCTAssertNil(DrawingStore.applyingGroup([], to: drawing))
    }

    func testApplyingUngroupOfKnownGroupIDClearsParentGroupIDOnEveryMember() {
        let groupID = UUID()
        var s1 = Shape(kind: .rect, geometry: ShapeGeometry(x: 0, y: 0, width: 10, height: 10))
        var s2 = Shape(kind: .rect, geometry: ShapeGeometry(x: 20, y: 20, width: 10, height: 10))
        s1.parentGroupID = groupID
        s2.parentGroupID = groupID
        let drawing = Drawing.makeBlank().insertingShape(s1).insertingShape(s2)

        let result = DrawingStore.applyingUngroup(groupID, to: drawing)

        XCTAssertNotNil(result)
        XCTAssertNil(result?.drawing.shape(id: s1.id)?.parentGroupID)
        XCTAssertNil(result?.drawing.shape(id: s2.id)?.parentGroupID)
        XCTAssertEqual(Set(result?.memberIDs ?? []), Set([s1.id, s2.id]))
    }

    func testApplyingUngroupOfUnknownGroupIDReturnsNil() {
        let drawing = Drawing.makeBlank().insertingShape(
            Shape(kind: .rect, geometry: ShapeGeometry(x: 0, y: 0, width: 10, height: 10))
        )
        XCTAssertNil(DrawingStore.applyingUngroup(UUID(), to: drawing), "a groupID no shape carries must be a no-op")
    }

    // MARK: - Item 2.12: setCalloutAnchor / setDimensionInfo / setListItems
    // / setTableCell / insertTable - receipt + persistence + no-op + error
    // path (testing-doctrine.md's "Store mutation" coverage shape).

    func testSetCalloutAnchorEmitsExactlyOneReceiptWithShapeIDAndAnchorKind() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        var drawing = try await store.upsert(Drawing(title: "Callout Gate Test"))
        let callout = Shape(kind: .callout, geometry: ShapeGeometry(x: 0, y: 0, width: 100, height: 40))
        drawing = try await store.insertShape(callout, for: drawing.id)

        let updated = try await store.setCalloutAnchor(.free(x: 200, y: 200), forShape: callout.id, in: drawing.id)
        XCTAssertEqual(updated.shape(id: callout.id)?.calloutAnchor, .free(x: 200, y: 200))

        let receipts = try await store.receipts(forDrawing: drawing.id)
        let calloutReceipts = receipts.filter { $0.receiptType == DrawingReceiptType.setCalloutAnchor.rawValue }
        XCTAssertEqual(calloutReceipts.count, 1)
        XCTAssertEqual(calloutReceipts.first?.payload["shapeID"], .string(callout.id.uuidString))
        XCTAssertEqual(calloutReceipts.first?.payload["anchorKind"], .string("free"))
    }

    func testSetCalloutAnchorToItsCurrentValueEmitsNoReceipt() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        var drawing = try await store.upsert(Drawing(title: "Callout NoOp Gate Test"))
        let callout = Shape(kind: .callout, geometry: ShapeGeometry(x: 0, y: 0, width: 100, height: 40), calloutAnchor: .free(x: 5, y: 5))
        drawing = try await store.insertShape(callout, for: drawing.id)

        let receiptsBefore = try await store.receipts(forDrawing: drawing.id).count
        _ = try await store.setCalloutAnchor(.free(x: 5, y: 5), forShape: callout.id, in: drawing.id)
        let receiptsAfter = try await store.receipts(forDrawing: drawing.id).count

        XCTAssertEqual(receiptsAfter, receiptsBefore, "setting a callout's anchor to its own current value must not append a receipt")
    }

    func testSetCalloutAnchorOfUnknownShapeIDThrowsWithoutPersisting() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let drawing = try await store.upsert(Drawing(title: "Callout ErrorPath Gate Test"))
        let unknownID = UUID()

        do {
            _ = try await store.setCalloutAnchor(.free(x: 0, y: 0), forShape: unknownID, in: drawing.id)
            XCTFail("expected DrawingStoreError.shapeNotFound")
        } catch DrawingStoreError.shapeNotFound(let id) {
            XCTAssertEqual(id, unknownID)
        }

        let receipts = try await store.receipts(forDrawing: drawing.id)
        XCTAssertTrue(receipts.filter { $0.receiptType == DrawingReceiptType.setCalloutAnchor.rawValue }.isEmpty)
    }

    func testSetDimensionInfoEmitsExactlyOneReceiptAndPersistsInfo() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        var drawing = try await store.upsert(Drawing(title: "DimensionInfo Gate Test"))
        let line = Shape(kind: .line, geometry: ShapeGeometry(x: 0, y: 0, width: 100, height: 0))
        drawing = try await store.insertShape(line, for: drawing.id)

        let info = ShapeDimensionInfo(units: .centimeter, precision: 2)
        let updated = try await store.setDimensionInfo(info, forShape: line.id, in: drawing.id)
        XCTAssertEqual(updated.shape(id: line.id)?.dimensionInfo, info)

        let receipts = try await store.receipts(forDrawing: drawing.id)
        let dimensionReceipts = receipts.filter { $0.receiptType == DrawingReceiptType.setDimensionInfo.rawValue }
        XCTAssertEqual(dimensionReceipts.count, 1)
        XCTAssertEqual(dimensionReceipts.first?.payload["units"], .string("centimeter"))
        XCTAssertEqual(dimensionReceipts.first?.payload["hasManualOverride"], .bool(false))
    }

    func testSetDimensionInfoToItsCurrentValueEmitsNoReceipt() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        var drawing = try await store.upsert(Drawing(title: "DimensionInfo NoOp Gate Test"))
        let line = Shape(kind: .line, geometry: ShapeGeometry(x: 0, y: 0, width: 100, height: 0), dimensionInfo: ShapeDimensionInfo(units: .point, precision: 1))
        drawing = try await store.insertShape(line, for: drawing.id)

        let receiptsBefore = try await store.receipts(forDrawing: drawing.id).count
        _ = try await store.setDimensionInfo(ShapeDimensionInfo(units: .point, precision: 1), forShape: line.id, in: drawing.id)
        let receiptsAfter = try await store.receipts(forDrawing: drawing.id).count

        XCTAssertEqual(receiptsAfter, receiptsBefore)
    }

    func testSetDimensionInfoOfUnknownShapeIDThrowsWithoutPersisting() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let drawing = try await store.upsert(Drawing(title: "DimensionInfo ErrorPath Gate Test"))
        let unknownID = UUID()

        do {
            _ = try await store.setDimensionInfo(ShapeDimensionInfo(), forShape: unknownID, in: drawing.id)
            XCTFail("expected DrawingStoreError.shapeNotFound")
        } catch DrawingStoreError.shapeNotFound(let id) {
            XCTAssertEqual(id, unknownID)
        }
    }

    func testSetListItemsEmitsExactlyOneReceiptWithItemCount() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        var drawing = try await store.upsert(Drawing(title: "ListItems Gate Test"))
        let s = Shape(kind: .rect, geometry: ShapeGeometry(x: 0, y: 0, width: 100, height: 100))
        drawing = try await store.insertShape(s, for: drawing.id)

        let items = [ShapeTextListItem(runs: [InlineRun(text: "one")]), ShapeTextListItem(runs: [InlineRun(text: "two")], level: 1)]
        let updated = try await store.setListItems(items, style: .ordered, forShape: s.id, in: drawing.id)
        XCTAssertEqual(updated.shape(id: s.id)?.text?.listItems, items)
        XCTAssertEqual(updated.shape(id: s.id)?.text?.listStyle, .ordered)

        let receipts = try await store.receipts(forDrawing: drawing.id)
        let listReceipts = receipts.filter { $0.receiptType == DrawingReceiptType.setListItems.rawValue }
        XCTAssertEqual(listReceipts.count, 1)
        XCTAssertEqual(listReceipts.first?.payload["itemCount"], .number(2))
    }

    func testSetListItemsPreservesExistingPlainRunsField() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        var drawing = try await store.upsert(Drawing(title: "ListItems Preserve Gate Test"))
        var s = Shape(kind: .rect, geometry: ShapeGeometry(x: 0, y: 0, width: 100, height: 100))
        s.text = ShapeText(runs: [InlineRun(text: "original plain text")])
        drawing = try await store.insertShape(s, for: drawing.id)

        let items = [ShapeTextListItem(runs: [InlineRun(text: "bullet")])]
        let updated = try await store.setListItems(items, style: .unordered, forShape: s.id, in: drawing.id)

        XCTAssertEqual(updated.shape(id: s.id)?.text?.runs.first?.text, "original plain text", "setListItems must not clear the pre-existing runs field")
    }

    func testSetListItemsToItsCurrentValueEmitsNoReceipt() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        var drawing = try await store.upsert(Drawing(title: "ListItems NoOp Gate Test"))
        var s = Shape(kind: .rect, geometry: ShapeGeometry(x: 0, y: 0, width: 100, height: 100))
        let items = [ShapeTextListItem(runs: [InlineRun(text: "one")])]
        s.text = ShapeText(listItems: items, listStyle: .task)
        drawing = try await store.insertShape(s, for: drawing.id)

        let receiptsBefore = try await store.receipts(forDrawing: drawing.id).count
        _ = try await store.setListItems(items, style: .task, forShape: s.id, in: drawing.id)
        let receiptsAfter = try await store.receipts(forDrawing: drawing.id).count

        XCTAssertEqual(receiptsAfter, receiptsBefore)
    }

    func testSetListItemsOfUnknownShapeIDThrowsWithoutPersisting() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let drawing = try await store.upsert(Drawing(title: "ListItems ErrorPath Gate Test"))
        let unknownID = UUID()

        do {
            _ = try await store.setListItems([ShapeTextListItem()], style: .unordered, forShape: unknownID, in: drawing.id)
            XCTFail("expected DrawingStoreError.shapeNotFound")
        } catch DrawingStoreError.shapeNotFound(let id) {
            XCTAssertEqual(id, unknownID)
        }
    }

    func testInsertTableEmitsExactlyOneInsertShapeReceiptWithTableKind() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let drawing = try await store.upsert(Drawing(title: "InsertTable Gate Test"))
        let table = DrawTable(rowCount: 2, columnCount: 2)

        let updated = try await store.insertTable(table, geometry: ShapeGeometry(x: 0, y: 0, width: table.totalWidth, height: table.totalHeight), for: drawing.id)
        XCTAssertEqual(updated.shapes.first?.kind, .table)
        XCTAssertEqual(updated.shapes.first?.table?.rowCount, 2)

        let receipts = try await store.receipts(forDrawing: drawing.id)
        let insertReceipts = receipts.filter { $0.receiptType == DrawingReceiptType.insertShape.rawValue }
        XCTAssertEqual(insertReceipts.count, 1)
        XCTAssertEqual(insertReceipts.first?.payload["kind"], .string("table"))
    }

    func testSetTableCellEmitsExactlyOneReceiptAndPersistsCellContent() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let table = DrawTable(rowCount: 2, columnCount: 2)
        var drawing = try await store.upsert(Drawing(title: "SetTableCell Gate Test"))
        drawing = try await store.insertTable(table, geometry: ShapeGeometry(x: 0, y: 0, width: table.totalWidth, height: table.totalHeight), for: drawing.id)
        let shapeID = try XCTUnwrap(drawing.shapes.first?.id)

        let cell = DrawTableCell(text: ShapeText(runs: [InlineRun(text: "A1")]))
        let updated = try await store.setTableCell(cell, row: 0, column: 0, forShape: shapeID, in: drawing.id)
        XCTAssertEqual(updated.shape(id: shapeID)?.table?.cell(row: 0, column: 0)?.text.plainText, "A1")

        let receipts = try await store.receipts(forDrawing: drawing.id)
        let cellReceipts = receipts.filter { $0.receiptType == DrawingReceiptType.setTableCell.rawValue }
        XCTAssertEqual(cellReceipts.count, 1)
        XCTAssertEqual(cellReceipts.first?.payload["row"], .number(0))
        XCTAssertEqual(cellReceipts.first?.payload["column"], .number(0))
    }

    func testSetTableCellAtOutOfRangePositionEmitsNoReceipt() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let table = DrawTable(rowCount: 1, columnCount: 1)
        var drawing = try await store.upsert(Drawing(title: "SetTableCell OutOfRange Gate Test"))
        drawing = try await store.insertTable(table, geometry: ShapeGeometry(x: 0, y: 0, width: table.totalWidth, height: table.totalHeight), for: drawing.id)
        let shapeID = try XCTUnwrap(drawing.shapes.first?.id)

        let receiptsBefore = try await store.receipts(forDrawing: drawing.id).count
        _ = try await store.setTableCell(DrawTableCell(), row: 9, column: 9, forShape: shapeID, in: drawing.id)
        let receiptsAfter = try await store.receipts(forDrawing: drawing.id).count

        XCTAssertEqual(receiptsAfter, receiptsBefore, "an out-of-range table cell position must not append a receipt")
    }

    func testSetTableCellOnAShapeWithNoTableEmitsNoReceipt() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        var drawing = try await store.upsert(Drawing(title: "SetTableCell NoTable Gate Test"))
        let rect = Shape(kind: .rect, geometry: ShapeGeometry(x: 0, y: 0, width: 10, height: 10))
        drawing = try await store.insertShape(rect, for: drawing.id)

        let receiptsBefore = try await store.receipts(forDrawing: drawing.id).count
        _ = try await store.setTableCell(DrawTableCell(), row: 0, column: 0, forShape: rect.id, in: drawing.id)
        let receiptsAfter = try await store.receipts(forDrawing: drawing.id).count

        XCTAssertEqual(receiptsAfter, receiptsBefore)
    }

    func testSetTableCellOfUnknownShapeIDThrowsWithoutPersisting() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let drawing = try await store.upsert(Drawing(title: "SetTableCell ErrorPath Gate Test"))
        let unknownID = UUID()

        do {
            _ = try await store.setTableCell(DrawTableCell(), row: 0, column: 0, forShape: unknownID, in: drawing.id)
            XCTFail("expected DrawingStoreError.shapeNotFound")
        } catch DrawingStoreError.shapeNotFound(let id) {
            XCTAssertEqual(id, unknownID)
        }
    }

    // MARK: - Item 2.12 pure application (UNGATED SHADOW, doctrine rule
    // 11) - see DrawingTests.swift for the corresponding no-DB tests of
    // applyingCalloutAnchor/applyingDimensionInfo/applyingListItems/
    // applyingTableCell.
}
