import XCTest
import Foundation
@testable import TesseraCore

// MARK: - DrawingStoreTests
//
// Contract sources: DrawingStore.swift's own doc comment ("every
// mutation appends a signed receipt... Receipt contract"),
// testing-doctrine.md rule 1 ("no receipt without a mutation" is a
// standing rule; its tests are mandatory per store method, both
// directions), and the KNOWN, AUDITED BUG named in this cluster's task
// brief (docs/p1-post-claim-audit-2026-08-15.md Class A item 1):
// DrawingStore's layer-mutation methods upsert + emit a receipt even
// when the underlying pure Drawing mutator no-op'd.
//
// DB-GATED (doctrine rule 11): every test in this file talks to a real
// TesseraDataLayer (Postgres + Valkey) and is skipped unless
// TESSERA_DB_INTEGRATION=1 is set AND the stores are actually reachable.
// Each contract here has an UNGATED SHADOW in DrawingTests.swift, which
// exercises the exact same "no-op on unknown id" contract directly
// against Drawing's pure mutators (the logic DrawingStore wraps) with
// no DB dependency - so a plain `swift test` still exercises the
// business logic even though the store-level wiring (and the bug in
// it) is only visible under the DB-gated pass.

private enum DrawTestDataLayer {
    /// Starts a real `TesseraDataLayer` against the default local
    /// Postgres/Valkey configuration. Skips the calling test (via
    /// `XCTSkip`) rather than failing when TESSERA_DB_INTEGRATION isn't
    /// set, or when it is set but the local stores aren't actually up -
    /// this is integration infrastructure, not something this test pass
    /// can guarantee is running.
    static func startedOrSkip() async throws -> TesseraDataLayer {
        guard ProcessInfo.processInfo.environment["TESSERA_DB_INTEGRATION"] == "1" else {
            throw XCTSkip("TESSERA_DB_INTEGRATION=1 not set - skipping DB-gated DrawingStore test (see rule 11's ungated shadow in DrawingTests.swift for the same contract without a DB).")
        }
        let layer = TesseraDataLayer()
        let outcome = await layer.start()
        guard case .ready = outcome else {
            throw XCTSkip("TesseraDataLayer did not reach .ready (\(outcome)) - local Postgres/Valkey not reachable.")
        }
        return layer
    }
}

final class DrawingStoreTests: DoctrineTestCase {
    override var doctrineTimeoutSeconds: TimeInterval { DoctrineTimeout.standard }

    // MARK: - Upsert: receipt + persistence (rule 1, mutation direction)

    func testUpsertOfNewDrawingEmitsExactlyOneUpsertReceiptWithDocumentedPayloadKeys() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let drawing = Drawing(title: "Gate Test Drawing")

        let saved = try await store.upsert(drawing)
        let receipts = try await store.receipts(forDrawing: saved.id)

        XCTAssertEqual(receipts.count, 1)
        let receipt = try XCTUnwrap(receipts.first)
        XCTAssertEqual(receipt.receiptType, DrawingReceiptType.upsert.rawValue)
        XCTAssertEqual(receipt.payload["title"], .string("Gate Test Drawing"))
        XCTAssertEqual(receipt.payload["shapeCount"], .number(0))

        let fetched = try await store.get(id: saved.id)
        XCTAssertEqual(fetched?.title, "Gate Test Drawing")
    }

    // MARK: - Delete: error path (not-found throws without writing)

    func testDeleteOfUnknownIDReturnsFalseAndEmitsNoReceipt() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let unknownID = UUID()

        let didDelete = try await store.delete(id: unknownID)
        XCTAssertFalse(didDelete)

        let receipts = try await store.receipts(forDrawing: unknownID)
        XCTAssertEqual(receipts.count, 0, "a delete of a nonexistent drawing must not append a delete receipt")
    }

    // MARK: - addLayer: always mutates, exactly one receipt (NOT a
    // no-op-detectable case: DrawLayer's own id is freshly generated by
    // the caller, so there is no "unknown id" for addLayer to reject -
    // Drawing.addingLayer always appends, per its own doc comment).

    func testAddLayerAlwaysMutatesAndEmitsExactlyOneLayerAddedReceipt() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let drawing = try await store.upsert(Drawing(title: "AddLayer Gate Test"))
        let newLayer = DrawLayer(name: "Background")

        let updated = try await store.addLayer(newLayer, to: drawing.id)
        XCTAssertEqual(updated.layers.map(\.id), [newLayer.id])

        let receipts = try await store.receipts(forDrawing: drawing.id)
        let layerAddedReceipts = receipts.filter { $0.receiptType == DrawingReceiptType.layerAdded.rawValue }
        XCTAssertEqual(layerAddedReceipts.count, 1)
    }

    // MARK: - No-op layer mutations: SUSPECTED BUG (doctrine rule 1,
    // suspected-bug protocol). Each of these asserts ZERO receipts for a
    // mutation on an unknown layer id, matching the pure Drawing mutator's
    // own no-op contract (see DrawingTests.swift). Confirmed failing at
    // HEAD per docs/p1-post-claim-audit-2026-08-15.md Class A item 1.

    func testRemoveLayerOfUnknownIDEmitsNoReceiptAndDoesNotPersist() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let drawing = try await store.upsert(Drawing(title: "RemoveLayer NoOp Gate Test"))
        let unknownLayerID = UUID()

        // XCTExpectFailure's failingBlock is synchronous (`() throws -> Void`),
        // so the async setup/action/measurement happens here, before the
        // block - only the plain assertion on already-computed values runs
        // inside it.
        let receiptsBefore = try await store.receipts(forDrawing: drawing.id).count
        _ = try? await store.removeLayer(unknownLayerID, from: drawing.id)
        let receiptsAfter = try await store.receipts(forDrawing: drawing.id).count

        XCTExpectFailure("SUSPECTED CODE BUG: DrawingStore.removeLayer upserts + emits drawing_layer_deleted even when the underlying Drawing.removingLayer no-op'd on an unknown layer id - violates receipts law (rule 1). See docs/p1-post-claim-audit-2026-08-15.md Class A item 1.") {
            XCTAssertEqual(receiptsAfter, receiptsBefore, "no-op layer removal must not append a receipt")
        }
    }

    func testRenameLayerOfUnknownIDEmitsNoReceiptAndDoesNotPersist() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let drawing = try await store.upsert(Drawing(title: "RenameLayer NoOp Gate Test"))
        let unknownLayerID = UUID()

        let receiptsBefore = try await store.receipts(forDrawing: drawing.id).count
        _ = try? await store.renameLayer(unknownLayerID, to: "New Name", in: drawing.id)
        let receiptsAfter = try await store.receipts(forDrawing: drawing.id).count

        XCTExpectFailure("SUSPECTED CODE BUG: DrawingStore.renameLayer upserts + emits drawing_layer_renamed even when the underlying Drawing.renamingLayer no-op'd on an unknown layer id - violates receipts law (rule 1). See docs/p1-post-claim-audit-2026-08-15.md Class A item 1.") {
            XCTAssertEqual(receiptsAfter, receiptsBefore, "no-op layer rename must not append a receipt")
        }
    }

    func testReorderLayersWithMismatchedOrderEmitsNoReceiptAndDoesNotPersist() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        var drawing = try await store.upsert(Drawing(title: "ReorderLayers NoOp Gate Test"))
        let onlyLayer = DrawLayer(name: "Only")
        drawing = try await store.addLayer(onlyLayer, to: drawing.id)
        let mismatchedOrder = [onlyLayer.id, UUID()]

        let receiptsBefore = try await store.receipts(forDrawing: drawing.id).count
        _ = try? await store.reorderLayers(mismatchedOrder, in: drawing.id)
        let receiptsAfter = try await store.receipts(forDrawing: drawing.id).count

        XCTExpectFailure("SUSPECTED CODE BUG: DrawingStore.reorderLayers upserts + emits drawing_layer_reordered even when the underlying Drawing.reorderingLayers no-op'd on a mismatched id set - violates receipts law (rule 1). See docs/p1-post-claim-audit-2026-08-15.md Class A item 1.") {
            XCTAssertEqual(receiptsAfter, receiptsBefore, "no-op layer reorder must not append a receipt")
        }
    }

    func testSetLayerVisibilityOfUnknownIDEmitsNoReceiptAndDoesNotPersist() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let drawing = try await store.upsert(Drawing(title: "SetLayerVisibility NoOp Gate Test"))
        let unknownLayerID = UUID()

        let receiptsBefore = try await store.receipts(forDrawing: drawing.id).count
        _ = try? await store.setLayerVisibility(unknownLayerID, isVisible: false, in: drawing.id)
        let receiptsAfter = try await store.receipts(forDrawing: drawing.id).count

        XCTExpectFailure("SUSPECTED CODE BUG: DrawingStore.setLayerVisibility upserts + emits drawing_layer_visibility_changed even when the underlying Drawing.settingLayerVisibility no-op'd on an unknown layer id - violates receipts law (rule 1). See docs/p1-post-claim-audit-2026-08-15.md Class A item 1.") {
            XCTAssertEqual(receiptsAfter, receiptsBefore, "no-op visibility change must not append a receipt")
        }
    }

    func testSetLayerLockOfUnknownIDEmitsNoReceiptAndDoesNotPersist() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let drawing = try await store.upsert(Drawing(title: "SetLayerLock NoOp Gate Test"))
        let unknownLayerID = UUID()

        let receiptsBefore = try await store.receipts(forDrawing: drawing.id).count
        _ = try? await store.setLayerLock(unknownLayerID, isLocked: true, in: drawing.id)
        let receiptsAfter = try await store.receipts(forDrawing: drawing.id).count

        XCTExpectFailure("SUSPECTED CODE BUG: DrawingStore.setLayerLock upserts + emits drawing_layer_lock_changed even when the underlying Drawing.settingLayerLock no-op'd on an unknown layer id - violates receipts law (rule 1). See docs/p1-post-claim-audit-2026-08-15.md Class A item 1.") {
            XCTAssertEqual(receiptsAfter, receiptsBefore, "no-op lock change must not append a receipt")
        }
    }

    // MARK: - Shape mutation error path

    func testDeleteShapeOfUnknownIDThrowsShapeNotFoundWithoutPersisting() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let drawing = try await store.upsert(Drawing(title: "DeleteShape ErrorPath Gate Test"))
        let unknownShapeID = UUID()

        do {
            _ = try await store.deleteShape(unknownShapeID, for: drawing.id)
            XCTFail("expected DrawingStoreError.shapeNotFound")
        } catch DrawingStoreError.shapeNotFound(let id) {
            XCTAssertEqual(id, unknownShapeID)
        }

        let receipts = try await store.receipts(forDrawing: drawing.id)
        let deleteShapeReceipts = receipts.filter { $0.receiptType == DrawingReceiptType.deleteShape.rawValue }
        XCTAssertEqual(deleteShapeReceipts.count, 0, "a failed shape delete must not append a deleteShape receipt")
    }

    // MARK: - Shape insert: receipt payload keys

    func testInsertShapeEmitsExactlyOneReceiptWithShapeIDAndKind() async throws {
        let layer = try await DrawTestDataLayer.startedOrSkip()
        let store = DrawingStore(dataLayer: layer)
        let drawing = try await store.upsert(Drawing(title: "InsertShape Gate Test"))
        let shape = Shape(kind: .ellipse, geometry: ShapeGeometry(x: 0, y: 0, width: 5, height: 5))

        _ = try await store.insertShape(shape, for: drawing.id)

        let receipts = try await store.receipts(forDrawing: drawing.id)
        let insertReceipts = receipts.filter { $0.receiptType == DrawingReceiptType.insertShape.rawValue }
        XCTAssertEqual(insertReceipts.count, 1)
        XCTAssertEqual(insertReceipts.first?.payload["shapeID"], .string(shape.id.uuidString))
        XCTAssertEqual(insertReceipts.first?.payload["kind"], .string("ellipse"))
    }
}
