import XCTest
@testable import TesseraCore

// MARK: - OVBADecompressorTests
//
// Contract: this track's brief (P2-D item 2.13, "OVBADecompressor.swift:
// MS-OVBA decompression... Pure function: compressed Data -> decompressed
// Data..., throwing on malformed input rather than crashing") + the
// [MS-OVBA] 2.4.1 CompressedContainer specification directly (this agent
// had no reference access to a real Microsoft-produced `vbaProject.bin`
// sample - see `MacroFixtures.swift`'s own header for the honest
// provenance statement testing-doctrine.md's item-5 instruction calls
// for). Round-trip cases use the hand-written literal-only encoder in
// `MacroFixtures.swift`; the copy-token path additionally gets ONE fully
// hand-worked-by-hand example (test 3 below) with the bit-width/offset
// arithmetic shown in the test's own comment, not generated by any
// encoder.

final class OVBADecompressorTests: DoctrineTestCase {

    // MARK: - Round trip (literal-only encoding)

    func testDecompressRoundTripsShortLiteralOnlyContainer() throws {
        let plaintext = Data("Attribute VB_Name = \"Module1\"\r\nSub Foo(x As Integer)\r\n    Shell \"cmd.exe\"\r\nEnd Sub\r\n".utf8)
        let compressed = makeLiteralOnlyOVBAContainer(plaintext)
        let decompressed = try OVBADecompressor.decompress(compressed)
        XCTAssertEqual(decompressed, plaintext)
    }

    func testDecompressRoundTripsContainerSpanningMultipleChunks() throws {
        let line = String(repeating: "X", count: 50) + "\r\n"
        let plaintext = Data(String(repeating: line, count: 100).utf8) // ~5200 bytes, > 1 fixture chunk
        let compressed = makeLiteralOnlyOVBAContainer(plaintext)
        let decompressed = try OVBADecompressor.decompress(compressed)
        XCTAssertEqual(decompressed, plaintext)
    }

    func testDecompressRoundTripsSingleByteContainer() throws {
        let plaintext = Data("A".utf8)
        let compressed = makeLiteralOnlyOVBAContainer(plaintext)
        let decompressed = try OVBADecompressor.decompress(compressed)
        XCTAssertEqual(decompressed, plaintext)
    }

    // MARK: - Hand-worked copy-token example
    //
    // Encodes the 4-byte plaintext "AAAA" as: a literal 'A' token,
    // followed by ONE copy token that reproduces the remaining "AAA".
    // Byte layout, worked by hand against [MS-OVBA] 2.4.1.1.5/2.4.1.3.19
    // (not generated by `makeLiteralOnlyOVBAContainer`, which never
    // emits copy tokens):
    //   0x01                        CompressedContainerSignature
    //   token data = [flag, 'A', copyTokenLow, copyTokenHigh] (4 bytes)
    //   CompressedChunkHeader (little-endian UInt16):
    //     bit 15 (compressed)      = 1
    //     bits 12-14 (signature)   = 0b011
    //     bits 0-11 (size-3)       = tokenData.count - 1 = 3
    //     -> 0x8000 | 0x3000 | 0x0003 = 0xB003 -> bytes [0x03, 0xB0]
    //   flag byte  = 0b00000010 (bit0 literal 'A', bit1 copy token)
    //   literal    = 0x41 ('A')
    //   copy token: at the moment this token is read, ONE byte ('A') has
    //     already been decompressed in this chunk, so differenceValue=1.
    //     CopyTokenHelp: smallest bitCount in 4...15 with 2^bitCount>=1
    //     is 4 -> lengthMask=0x0FFF, offsetMask=0xF000.
    //     Want length=3 ("AAA") -> lengthField = length-3 = 0.
    //     Want backOffset=1 (copy the immediately-preceding byte) ->
    //     temp1 = (backOffset-1) << (16-bitCount) = 0 << 12 = 0.
    //     token = temp1 | lengthField = 0x0000 -> bytes [0x00, 0x00].
    // Decompressing byte-by-byte: start with "A", then 3 copies of
    // "the byte 1 position back", each extending the output by one byte
    // and re-reading the just-appended byte -> "A" + "A" + "A" + "A".
    func testDecompressHandWorkedCopyTokenExampleProducesAAAA() throws {
        var bytes: [UInt8] = [0x01]
        let tokenDataLen = 1 + 1 + 2 // flag + literal + copy token
        let sizeField = UInt16(tokenDataLen - 1)
        let header: UInt16 = 0x8000 | (0b011 << 12) | sizeField
        bytes.append(UInt8(header & 0xFF))
        bytes.append(UInt8((header >> 8) & 0xFF))
        bytes.append(0b0000_0010)
        bytes.append(0x41)
        bytes.append(0x00)
        bytes.append(0x00)

        let decompressed = try OVBADecompressor.decompress(Data(bytes))
        XCTAssertEqual(String(decoding: decompressed, as: UTF8.self), "AAAA")
    }

    // MARK: - Uncompressed (raw) chunk

    func testDecompressRawChunkCopiesExactly4096LiteralBytes() throws {
        var bytes: [UInt8] = [0x01]
        // Raw chunk: CompressedChunkFlag=0, CompressedChunkSize field
        // MUST be 4095 (on-wire size 4095+3=4098 = 2-byte header + 4096
        // literal bytes).
        let header: UInt16 = (0b011 << 12) | 0x0FFF
        bytes.append(UInt8(header & 0xFF))
        bytes.append(UInt8((header >> 8) & 0xFF))
        let payload = (0..<4096).map { UInt8($0 % 256) }
        bytes.append(contentsOf: payload)

        let decompressed = try OVBADecompressor.decompress(Data(bytes))
        XCTAssertEqual([UInt8](decompressed), payload)
    }

    // MARK: - Malformed input (throws, never crashes)

    func testDecompressThrowsOnEmptyContainer() {
        XCTAssertThrowsError(try OVBADecompressor.decompress(Data())) { error in
            XCTAssertEqual(error as? OVBADecompressorError, .emptyContainer)
        }
    }

    func testDecompressThrowsOnBadSignatureByte() {
        XCTAssertThrowsError(try OVBADecompressor.decompress(Data([0x02, 0x00, 0x00]))) { error in
            XCTAssertEqual(error as? OVBADecompressorError, .invalidSignature(found: 0x02))
        }
    }

    func testDecompressThrowsOnTruncatedChunkHeader() {
        // Signature byte, then a single dangling header byte.
        XCTAssertThrowsError(try OVBADecompressor.decompress(Data([0x01, 0x00]))) { error in
            guard case .truncatedChunkHeader = error as? OVBADecompressorError else {
                return XCTFail("expected truncatedChunkHeader, got \(error)")
            }
        }
    }

    func testDecompressThrowsOnInvalidChunkSignatureBits() {
        // header bits 12-14 must be 0b011; set them to 0b000 instead.
        let badHeader: UInt16 = 0x8000 | 0x0000 | 0x0003
        let bytes: [UInt8] = [0x01, UInt8(badHeader & 0xFF), UInt8((badHeader >> 8) & 0xFF), 0x00, 0x00]
        XCTAssertThrowsError(try OVBADecompressor.decompress(Data(bytes))) { error in
            guard case .invalidChunkSignature(let found, _) = error as? OVBADecompressorError else {
                return XCTFail("expected invalidChunkSignature, got \(error)")
            }
            XCTAssertEqual(found, 0)
        }
    }

    func testDecompressThrowsOnChunkSizeRunningPastEndOfInput() {
        // Declares a chunk far larger than the bytes actually present.
        let header: UInt16 = 0x8000 | (0b011 << 12) | 0x0FFF
        let bytes: [UInt8] = [0x01, UInt8(header & 0xFF), UInt8((header >> 8) & 0xFF)]
        XCTAssertThrowsError(try OVBADecompressor.decompress(Data(bytes))) { error in
            guard case .truncatedChunkData = error as? OVBADecompressorError else {
                return XCTFail("expected truncatedChunkData, got \(error)")
            }
        }
    }

    func testDecompressThrowsOnCopyTokenWithNothingToCopyFrom() {
        // A copy token as the VERY FIRST token in a chunk: nothing has
        // been decompressed yet, so any back-reference is out of range.
        var bytes: [UInt8] = [0x01]
        let tokenDataLen = 1 + 2 // flag + copy token, no literal first
        let sizeField = UInt16(tokenDataLen - 1)
        let header: UInt16 = 0x8000 | (0b011 << 12) | sizeField
        bytes.append(UInt8(header & 0xFF))
        bytes.append(UInt8((header >> 8) & 0xFF))
        bytes.append(0b0000_0001) // bit0 = copy token
        bytes.append(0x00)
        bytes.append(0x00)

        XCTAssertThrowsError(try OVBADecompressor.decompress(Data(bytes))) { error in
            guard case .copyTokenOffsetOutOfRange = error as? OVBADecompressorError else {
                return XCTFail("expected copyTokenOffsetOutOfRange, got \(error)")
            }
        }
    }

    // MARK: - bitCount(forDifferenceValue:) property (MS-OVBA 2.4.1.3.19)

    func testBitCountForDifferenceValueIsSmallestPowerOfTwoCoveringIt() {
        // Spec floor of 4, and the smallest bitCount such that
        // 2^bitCount >= differenceValue.
        XCTAssertEqual(OVBADecompressor.bitCount(forDifferenceValue: 0), 4)
        XCTAssertEqual(OVBADecompressor.bitCount(forDifferenceValue: 1), 4)
        XCTAssertEqual(OVBADecompressor.bitCount(forDifferenceValue: 16), 4)
        XCTAssertEqual(OVBADecompressor.bitCount(forDifferenceValue: 17), 5)
        XCTAssertEqual(OVBADecompressor.bitCount(forDifferenceValue: 4096), 12)
    }
}
