import Foundation

//===----------------------------------------------------------------------===//
//  TocController.swift
//  Tessera Studio
//
//  Table-of-contents generation for Writer (P2-C item 2.5,
//  studio-expansion-design-refinement-2026-08-14.md's Writer cluster;
//  design contract detail in docs/.scratch/sota-p2-core-report.md
//  section "2.5 ToC"). A `.toc` block's `attributes["toc"]` holds the
//  persistent `TocSpec` (see `Block/toc`); its `children` are
//  GENERATED entry paragraphs (derived-never-stored - regenerated by
//  `regenerate(_:in:)`, never hand-edited), each carrying its own
//  `attributes["tocEntry"]` (`TocEntry` - see `Block/tocEntry`).
//
//  Pure and stateless, matching FieldController/RevisionController/
//  StyleRegistry/TransformController/QueryEngine in this same wave
//  family: `regenerate` takes a `DocumentAST` and returns a new one
//  plus a `TocRegenerationResult`, never touching `DocStore`. A future
//  `DocStore` integration (`regenerateToc(for:)`, see the wave's
//  wiringNotes) is the one place that both calls this and appends the
//  `doc_toc_regenerated` receipt - only when `result.changed` is
//  `true`, this file's own "did anything actually change" signal
//  (see `TocRegenerationResult.changed`), mirroring
//  `FieldController.refresh`'s "plain `!=` check" boundary and
//  `RevisionResolution.isEmpty`'s shape.
//
//  **Collection algorithm.** Walks the document in document order
//  (`headingCandidateOrder`, a `depthFirstOrder`-style walk that never
//  descends into a `.toc` block's own children - a TOC's generated
//  entries are never candidates themselves, the same posture
//  `DocumentSearchIndex`/`Doc.plainText` already take toward `.toc`
//  children). For each block, `candidateLevel` picks the FIRST of the
//  following that applies:
//    1. `spec.extraStyles[block.styleRef]` (Word's `\t "Style,Level"`
//       switch) - an EXPLICIT override, so it is the only source that
//       bypasses the `[fromLevel, toLevel]` range filter below. This
//       matches Word's own documented `\t` behavior (MS field-code
//       reference, see the sota report's 2.5 evidence line): `\t`
//       entries are ADDITIONAL to whatever `\o`'s range already
//       collects, not bounded by it - a judgment call recorded here
//       (and in this wave's findings file) since the design contract
//       names the field but not this bypass rule explicitly.
//    2. `block.type == .heading`'s intrinsic `attributes["level"]`.
//    3. The block's `styleRef` resolved through
//       `StyleRegistry.chain(from:in:)` (leaf-to-root, i.e. the
//       block's OWN style checked before its ancestors) for the
//       first style whose `name` matches the "Heading N" convention -
//       see `headingLevel(fromStyleName:)`. No dedicated `level`
//       field exists on `StyleDefinition` today (see
//       `StyleRegistry.swift`); "Heading N" is this codebase's own
//       existing naming convention (`StyleRegistryTests`,
//       `DocStoreTests` both already construct a style named
//       "Heading 1"). Reuses `StyleRegistry`'s own basedOn-chain walk
//       (widened from `private` to internal for this file's reuse -
//       see `StyleRegistry.swift`'s `chain(from:in:)`) rather than
//       reimplementing style inheritance, per the design contract's
//       explicit instruction.
//    4. `block.attributes["outlineLevel"]`, only when
//       `spec.includeOutlineLevels` is set (Word's `\u` switch: pick
//       up paragraphs carrying a manually-applied outline level even
//       without a heading style or intrinsic heading type). This
//       attribute key is introduced by this controller - no
//       pre-existing "paragraph outline level" convention exists
//       elsewhere in this codebase (the sheets-only
//       `SubtotalEngine`/`Sheet.rowOutlineLevels` concept is a
//       different, row-indexed thing).
//  Sources 2-4 are all filtered to `[spec.fromLevel, spec.toLevel]`;
//  source 1 is not (see above).
//
//  **Page numbers.** Exactly the `FieldKind.page` stance (see
//  `FieldController.swift`'s file header): `pageText` is cached and
//  `pageDirty` stays `true` until a paginator context exists (none
//  does at P1/P2) - `regenerate` never invents a page number itself.
//  A regenerated entry whose `targetBlockID` matches a PRIOR entry
//  reuses that prior entry's `pageText`/`pageDirty` verbatim; a
//  brand-new entry starts at `pageText: "", pageDirty: true` -
//  `FieldSpec`'s own "set on creation, left true forever" default,
//  generalized here.
//
//  **Idempotence.** Calling `regenerate` twice with no intervening
//  document change produces `changed == false` on the second call and
//  returns the INPUT `ast` untouched (not a structurally-equal copy -
//  the same value, never rebuilt) - the exact `RevisionResolution`/
//  `FieldController` "no-op means no mutation at all" contract. This
//  holds because entry pageText/pageDirty is carried over by
//  `targetBlockID` match (point above) and `headingCandidateOrder` is
//  a pure function of the document, so an unchanged document always
//  re-derives the same ordered entry list the previous regenerate
//  call already wrote.
//
//  **Export/import (design notes, not implemented in this file - no
//  I/O files are in this track's scope this wave):** export should
//  serialize a real ODF `text:table-of-content` /
//  `text:table-of-content-source` (carrying `fromLevel`/`toLevel` as
//  `outline-level`, `extraStyles` as additional `text:index-source-
//  style` entries, `hyperlink` as `text:index-scope`'s hyperlink
//  flag) or a Word `{ TOC \o "from-to" \h \z \u \t "Style,Level" }`
//  field so LO/Word recompute the TOC themselves on open (plan 4a
//  stance - see this wave's findings file for the full shape). Import
//  should populate a `.toc` block's children directly from LO's own
//  resolved TOC paragraph text (bypassing `regenerate` entirely for
//  that first population, since the source document's own pagination
//  is real) and record the spec's `\o`/`\h`/`\u`/`\t` switches back
//  into `TocSpec`.
//===----------------------------------------------------------------------===//

// MARK: - TocTabLeader

/// The character `TocController`'s future renderer draws between an
/// entry's text and its `pageText` - a rendering/export concern this
/// controller stores but never itself reads (see `TocSpec.tabLeader`).
public enum TocTabLeader: String, Codable, Sendable, Hashable, CaseIterable {
    case dots
    case dashes
    case underscore
    /// No leader - text and page number sit with a plain gap between
    /// them. Named `noLeader` rather than `none` to avoid reading like
    /// `Optional.none` at call sites.
    case noLeader
}

// MARK: - TocSpec

/// A `.toc` block's persistent state, stored via `attributes["toc"]` -
/// see `Block/toc`. Field names and Word field-switch mapping per the
/// design contract: `fromLevel`/`toLevel` (`\o "from-to"`),
/// `includeOutlineLevels` (`\u`), `hyperlink` (`\h`), `extraStyles`
/// (`\t "Style,Level"`), `tabLeader` (no direct switch - Word derives
/// it from the applied TOC style; stored explicitly here since this
/// codebase has no TOC-specific style family yet).
public struct TocSpec: Codable, Sendable, Hashable {
    /// Shallowest heading level collected, inclusive (Word default 1).
    public var fromLevel: Int
    /// Deepest heading level collected, inclusive (Word default 3).
    public var toLevel: Int
    /// Also collect paragraphs carrying a manually-applied
    /// `attributes["outlineLevel"]` within `[fromLevel, toLevel]`,
    /// even when they are neither `.heading` nor styled with a
    /// heading-family style (Word's `\u` switch).
    public var includeOutlineLevels: Bool
    /// Whether a future renderer should make each entry a jump link
    /// to `targetBlockID` (Word's `\h` switch). Not read by
    /// `regenerate` itself - a rendering concern.
    public var hyperlink: Bool
    /// Explicit style -> level overrides (Word's `\t "Style,Level"`
    /// switch), keyed by the style's own id in `DocumentMeta.styles`.
    /// Entries whose `styleRef` matches a key here are collected at
    /// the given level regardless of `[fromLevel, toLevel]` - see the
    /// file header's collection-algorithm note.
    public var extraStyles: [UUID: Int]
    /// The leader drawn between an entry's text and its page number.
    /// Rendering concern only - see `TocTabLeader`.
    public var tabLeader: TocTabLeader

    public init(
        fromLevel: Int = 1,
        toLevel: Int = 3,
        includeOutlineLevels: Bool = false,
        hyperlink: Bool = true,
        extraStyles: [UUID: Int] = [:],
        tabLeader: TocTabLeader = .dots
    ) {
        self.fromLevel = fromLevel
        self.toLevel = toLevel
        self.includeOutlineLevels = includeOutlineLevels
        self.hyperlink = hyperlink
        self.extraStyles = extraStyles
        self.tabLeader = tabLeader
    }
}

// MARK: - TocEntry

/// One generated ToC entry paragraph's persistent state, stored via
/// `attributes["tocEntry"]` - see `Block/tocEntry`. The entry's
/// display TEXT (a snapshot of the target heading's own text at the
/// last `regenerate` call) lives in the entry block's own `content`,
/// the same "cached resolved text lives in `content`, structural data
/// lives in the attribute" split `FieldSpec`/`Block/field` already
/// use.
public struct TocEntry: Codable, Sendable, Hashable {
    /// The heading (or heading-family-styled, or outline-level)
    /// block this entry points at.
    public var targetBlockID: UUID
    /// The resolved ToC level (NOT necessarily the target's raw
    /// heading level when an `extraStyles` override applied).
    public var level: Int
    /// Cached page-number text. Empty until a paginator context
    /// exists - see the file header's "page numbers" note.
    public var pageText: String
    /// `true` until a paginator context exists to resolve `pageText`
    /// - exactly `FieldSpec.dirty`'s stance for `.page`/`.numPages`/
    /// `.ref`, generalized to ToC entries.
    public var pageDirty: Bool

    public init(targetBlockID: UUID, level: Int, pageText: String = "", pageDirty: Bool = true) {
        self.targetBlockID = targetBlockID
        self.level = level
        self.pageText = pageText
        self.pageDirty = pageDirty
    }
}

// MARK: - Block + Toc

extension Block {
    /// Reads/writes the block's ``TocSpec`` via `attributes["toc"]`.
    /// Same bridge shape as ``Block/shape``/``Block/frame``/
    /// ``Block/chart``/``Block/field``/``Block/media`` and for the
    /// same reason: `TocSpec`'s own `Codable` conformance stays the
    /// single source of truth for the wire shape. Gated to `.toc`
    /// blocks, matching those bridges (unlike `Block/tocEntry` below,
    /// which is a per-entry-paragraph attribute, not per-container).
    public var toc: TocSpec? {
        get {
            guard type == .toc, let raw = attributes["toc"] else { return nil }
            guard let data = try? JSONEncoder().encode(raw) else { return nil }
            return try? JSONDecoder().decode(TocSpec.self, from: data)
        }
        set {
            guard type == .toc else { return }
            guard let newValue else {
                attributes.removeValue(forKey: "toc")
                return
            }
            guard let data = try? JSONEncoder().encode(newValue),
                  let raw = try? JSONDecoder().decode(AnyCodable.self, from: data) else { return }
            attributes["toc"] = raw
        }
    }
}

// MARK: - Block + TocEntry

extension Block {
    /// Reads/writes the block's ``TocEntry`` via
    /// `attributes["tocEntry"]`. NOT gated to one `BlockType` - a ToC
    /// entry paragraph is an ordinary `.paragraph` block carrying this
    /// one extra attribute, the same "no type gate" posture
    /// `Block/styleRef` already takes (see `StyleRegistry.swift`) and
    /// for the same reason: the attribute's presence, not the block's
    /// type, is what marks it as an entry.
    public var tocEntry: TocEntry? {
        get {
            guard let raw = attributes["tocEntry"] else { return nil }
            guard let data = try? JSONEncoder().encode(raw) else { return nil }
            return try? JSONDecoder().decode(TocEntry.self, from: data)
        }
        set {
            guard let newValue else {
                attributes.removeValue(forKey: "tocEntry")
                return
            }
            guard let data = try? JSONEncoder().encode(newValue),
                  let raw = try? JSONDecoder().decode(AnyCodable.self, from: data) else { return }
            attributes["tocEntry"] = raw
        }
    }
}

// MARK: - TocRegenerationResult

/// The result of one `TocController.regenerate` call. Shaped for a
/// future `DocStore` integration to turn directly into a receipt -
/// `receiptType` is the matching `DocReceiptType` raw value, `payload`
/// is the structural summary in the `[String: JSONValue]` shape
/// `appendReceipt(entityID:receiptType:payload:)` already takes -
/// mirrors `RevisionResolution`'s own receipt-emission boundary: this
/// type does not append anything itself.
public struct TocRegenerationResult: Sendable, Equatable {
    public let tocBlockID: UUID
    /// The entries now in effect (whether or not this call changed
    /// anything - callers reading "what does the ToC look like now"
    /// don't need to branch on `changed`).
    public let entries: [TocEntry]
    /// `false` when `tocBlockID` wasn't a valid `.toc` block with a
    /// spec, OR the freshly-collected entry list is IDENTICAL (same
    /// order, same `targetBlockID`/`level`/`pageText`/`pageDirty`) to
    /// what was already there - the signal a `DocStore` integration
    /// uses to skip the mutation + receipt entirely (doctrine: no
    /// receipt without a mutation). `true` means the returned `ast`
    /// differs from the input.
    public let changed: Bool
    public let receiptType: String

    public init(tocBlockID: UUID, entries: [TocEntry], changed: Bool, receiptType: String) {
        self.tocBlockID = tocBlockID
        self.entries = entries
        self.changed = changed
        self.receiptType = receiptType
    }

    public var entryCount: Int { entries.count }
    public var dirtyPageCount: Int { entries.filter(\.pageDirty).count }

    /// The receipt payload a future `DocStore` integration appends
    /// verbatim - entry count + dirty-page count per the design
    /// contract's own receipt line.
    public var payload: [String: JSONValue] {
        [
            "tocBlockID": .string(tocBlockID.uuidString),
            "entryCount": .number(Double(entryCount)),
            "dirtyPageCount": .number(Double(dirtyPageCount)),
        ]
    }
}

// MARK: - TocController

/// Pure ToC collection/regeneration over `DocumentAST` - peer of
/// `FieldController`/`RevisionController`/`StyleRegistry`: a plain
/// namespace of static functions, no state, no `DocStore` dependency.
/// See the file header for the full design.
public enum TocController {

    /// Regenerate `tocBlockID`'s entry children from the document's
    /// current headings. A no-op (`changed == false`, `ast` returned
    /// untouched) when `tocBlockID` isn't a `.toc` block with a
    /// `TocSpec`, or when the freshly-collected entries are identical
    /// to what was already there - see the file header's idempotence
    /// note.
    public static func regenerate(_ tocBlockID: UUID, in ast: DocumentAST) -> (ast: DocumentAST, result: TocRegenerationResult) {
        let receiptType = DocReceiptType.regenerateToc.rawValue
        guard let tocBlock = ast.blocks[tocBlockID], tocBlock.type == .toc, let spec = tocBlock.toc else {
            return (ast, TocRegenerationResult(tocBlockID: tocBlockID, entries: [], changed: false, receiptType: receiptType))
        }

        let registry = ast.meta.styles
        var priorByTarget: [UUID: TocEntry] = [:]
        var priorEntries: [TocEntry] = []
        // Parallel to `priorEntries`: each entry child's own CACHED
        // display text (see the file header - the label lives in the
        // entry block's `content`, not in `TocEntry` itself). Compared
        // alongside `priorEntries` below so a heading whose TEXT
        // changed (but not its target/level/page state) still counts
        // as a real change - otherwise a renamed heading would leave a
        // stale label in the ToC forever, violating derived-never-
        // stored the moment only the label needed re-deriving.
        var priorTexts: [String] = []
        for childID in tocBlock.children {
            guard let childBlock = ast.blocks[childID], let entry = childBlock.tocEntry else { continue }
            priorEntries.append(entry)
            priorTexts.append(childBlock.content.map(\.text).joined())
            priorByTarget[entry.targetBlockID] = entry
        }

        var newEntries: [TocEntry] = []
        var newTexts: [String] = []
        var headingText: [UUID: String] = [:]
        for blockID in headingCandidateOrder(in: ast) where blockID != tocBlockID {
            guard let block = ast.blocks[blockID] else { continue }
            guard let level = candidateLevel(for: block, spec: spec, registry: registry) else { continue }
            let prior = priorByTarget[blockID]
            let text = block.content.map(\.text).joined()
            newEntries.append(TocEntry(
                targetBlockID: blockID,
                level: level,
                pageText: prior?.pageText ?? "",
                pageDirty: prior?.pageDirty ?? true
            ))
            newTexts.append(text)
            headingText[blockID] = text
        }

        guard newEntries != priorEntries || newTexts != priorTexts else {
            return (ast, TocRegenerationResult(tocBlockID: tocBlockID, entries: priorEntries, changed: false, receiptType: receiptType))
        }

        var result = ast
        for oldChildID in tocBlock.children {
            result.blocks.removeValue(forKey: oldChildID)
        }
        var newChildIDs: [UUID] = []
        for entry in newEntries {
            var entryBlock = Block(
                type: .paragraph,
                content: [InlineRun(text: headingText[entry.targetBlockID] ?? "")],
                parentID: tocBlockID
            )
            entryBlock.tocEntry = entry
            result.blocks[entryBlock.id] = entryBlock
            newChildIDs.append(entryBlock.id)
        }
        var updatedTocBlock = tocBlock
        updatedTocBlock.children = newChildIDs
        result.blocks[tocBlockID] = updatedTocBlock

        return (result, TocRegenerationResult(tocBlockID: tocBlockID, entries: newEntries, changed: true, receiptType: receiptType))
    }

    // MARK: - Collection

    /// `ast`'s blocks in document order, never descending into a
    /// `.toc` block's own children (its generated entries are never
    /// candidates - see the file header). Includes the `.toc` blocks
    /// themselves (harmless: `candidateLevel` never matches a `.toc`
    /// block, since it has no `styleRef`/heading type/outline level of
    /// its own by construction).
    private static func headingCandidateOrder(in ast: DocumentAST) -> [UUID] {
        var out: [UUID] = []
        func walk(_ id: UUID) {
            guard let block = ast.blocks[id] else { return }
            out.append(id)
            guard block.type != .toc else { return }
            for child in block.children { walk(child) }
        }
        for root in ast.rootChildren { walk(root) }
        return out
    }

    /// The ToC level `block` should be collected at, or `nil` if it
    /// isn't a candidate at all - see the file header's 4-source
    /// priority list.
    private static func candidateLevel(for block: Block, spec: TocSpec, registry: [UUID: StyleDefinition]) -> Int? {
        if let styleRef = block.styleRef, let explicitLevel = spec.extraStyles[styleRef] {
            return explicitLevel
        }
        if block.type == .heading,
           let level = block.attributes["level"]?.intValue,
           level >= spec.fromLevel, level <= spec.toLevel {
            return level
        }
        if let styleRef = block.styleRef,
           let level = headingFamilyLevel(styleRef: styleRef, registry: registry),
           level >= spec.fromLevel, level <= spec.toLevel {
            return level
        }
        if spec.includeOutlineLevels,
           let level = block.attributes["outlineLevel"]?.intValue,
           level >= spec.fromLevel, level <= spec.toLevel {
            return level
        }
        return nil
    }

    /// Walks `styleRef`'s `basedOn` chain leaf-to-root (the block's
    /// OWN style checked before its ancestors) via
    /// `StyleRegistry.chain(from:in:)`, returning the first style
    /// whose name matches the "Heading N" convention - see the file
    /// header. A dangling `styleRef` (absent from `registry`) yields
    /// an empty chain (`chain`'s own documented fail-soft behavior),
    /// so this simply returns `nil` rather than treating it as an
    /// error.
    private static func headingFamilyLevel(styleRef: UUID, registry: [UUID: StyleDefinition]) -> Int? {
        for style in StyleRegistry.chain(from: styleRef, in: registry).reversed() {
            if let level = headingLevel(fromStyleName: style.name) {
                return level
            }
        }
        return nil
    }

    /// Parses the "Heading N" naming convention (case-insensitive;
    /// matches this codebase's own `StyleRegistryTests`/`DocStoreTests`
    /// fixtures, which already construct a style literally named
    /// "Heading 1"). Any other name (including "Heading" alone, or a
    /// non-integer suffix) returns `nil`.
    private static func headingLevel(fromStyleName name: String) -> Int? {
        let prefix = "heading "
        let lower = name.lowercased()
        guard lower.hasPrefix(prefix) else { return nil }
        return Int(lower.dropFirst(prefix.count).trimmingCharacters(in: .whitespaces))
    }
}
